name: Publish

on:
  release:
    types: 
      - published
      - edited

jobs:
  build:
    name: Build and tag a new version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the current code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: ${{ github.event.release.tag_name }}

      - name: Configure the runtime node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc

      - name: Install project dependencies
        run: npm ci

      - name: Build a production release
        run: npm run build

      - name: Distribute the latest tagged release
        id: tag
        uses: teunmooij/github-versioned-release@3edf649c6e5e5e976d43f2584b15bdc8b4c8f0df # v1.2.1
        with:
          template: javascript-action
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create a branch for tagged release
        run: |
          git fetch origin "$SHA"
          git checkout -b "release/$TAG" "$SHA"
          git push origin "release/$TAG"
        env:
          TAG: ${{ github.event.release.tag_name }}
          SHA: ${{ steps.tag.outputs.sha }}
